# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=b'PENDING', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL)),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usercontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=b'ACCEPTED', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('ext', models.CharField(default=b'', max_length=20)),
                ('phoneno', models.CharField(default=b'', max_length=200)),
                ('mobileno', models.CharField(max_length=200)),
                ('profilepic', models.FileField(upload_to=b'')),
                ('deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_date', models.DateTimeField(auto_now_add=True)),
                ('aboutme', models.CharField(default=b'', max_length=2000)),
                ('skills', models.CharField(default=b'', max_length=1000)),
                ('emailverified', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=1000)),
                ('skypeid', models.CharField(max_length=1000)),
                ('membertype', models.CharField(default=b'INDIVIDUAL', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
