# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teaminvites_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aboutname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
