# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_aboutname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='aboutname',
            new_name='aboutteam',
        ),
    ]
