# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_relprojectportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relprojectportfolio',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='relprojectportfolio',
            name='project',
        ),
        migrations.DeleteModel(
            name='relProjectPortfolio',
        ),
    ]
