# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160915_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 13, 50, 31, 281000)),
        ),
        migrations.AlterField(
            model_name='project',
            name='lastupdate_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 13, 50, 31, 281000)),
        ),
    ]
