# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('ext', models.CharField(default='', max_length=20)),
                ('phoneno', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(max_length=200)),
                ('profilepic', models.FileField(upload_to='')),
                ('deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_date', models.DateTimeField(auto_now_add=True)),
                ('aboutme', models.CharField(default='', max_length=2000)),
                ('skills', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
