# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_relprojectportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='uuid',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
