"""
Django settings for onlineportfolio project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-71ug(il^xt+-kr(4#zf68n!*2lga*_s1541&idb$f@#rfmw6*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['event.127.0.0.1','127.0.0.1','localhost','college.127.0.0.1']


#SUBDOMAIN_URLCONFS = {
# The format for these is 'subdomain': 'urlconf'
#None: 'onlineportfolio.urls',
#'event': 'onlineportfolio.urls',
#}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'notifications',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'url_tools',
    'sorl.thumbnail',
    'account',
    'dashboard',
    'portfolio',
    'project',
    'hitcount',
    'django.contrib.sites',
    'django_comments',
    'django.contrib.humanize',
    'public',
    'team'
]

ROOT_URLCONF = 'onlineportfolio.urls'

SITE_ID = 1

MIDDLEWARE_CLASSES = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'subdomains.middleware.SubdomainURLRoutingMiddleware',
    'onlineportfolio.middleware.SimpleSubdomainMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'url_tools.context_processors.current_url'
            ],
        },
    },
]

WSGI_APPLICATION = 'onlineportfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'onlineport',
        'USER': 'postgres',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


#SESSION_COOKIE_DOMAIN = '.localhost'



'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd7mksdi2pdscnk',
        'USER': 'emtpqohlzyhjol',
        'PASSWORD': 'CQu_ILfO2Nh_hf5iBrlLYt1Ny-',
        'HOST': 'ec2-23-21-235-126.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}'''


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, "static")
]

#STATIC_ROOT = os.path.join(BASE_DIR, "static")

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

LOGIN_URL = '/account/signin/'

PROJECT_ROOT = BASE_DIR

EMAIL_HOST_USER = "parmjeet@ameotech.com"
EMAIL_HOST_PASSWORD = "roar@dude1"

SECRET_KEY = "SAJHFRWAJSFjJHFJWDSMkjJSDJW"

#import dj_database_url

#DATABASES['default'] =  dj_database_url.config()

