# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_template',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
